language: objective-c
osx_image: xcode8
install:
- gem install xcpretty
script:
- set -o pipefail && xcodebuild -workspace ColorSpaces.xcworkspace -scheme 'ColorSpaces-Mac' test | xcpretty -c
- set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace ./ColorSpaces.xcworkspace -scheme ColorSpaces-iOS -destination 'platform=iOS Simulator,name=iPhone 6s Plus'  build test | xcpretty
